#!/usr/bin/env python3
"""
EKF Debug Visualization Script

Reads the CSV file generated by the VESC driver EKF debug mode and plots
all relevant signals to help diagnose odometry drift issues.

Usage:
    python3 plot_ekf_debug.py [path_to_csv]
    
Default CSV path: /home/orin/roboracer_ws/data/debug/ekf_debug.csv

Note: This script runs headless (no display required) and saves plots to PNG files.
"""

import sys
import os
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend (no display required)
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from datetime import datetime

def load_data(filename='/home/orin/roboracer_ws/data/debug/ekf_debug.csv'):
    """Load EKF debug data from CSV file."""
    try:
        data = np.loadtxt(filename, delimiter=',', skiprows=1)
        print(f"Loaded {len(data)} samples from {filename}")
        return data
    except FileNotFoundError:
        print(f"Error: File not found: {filename}")
        print("Make sure the vesc_driver is running with debug_ekf=true")
        print(f"Expected location: {filename}")
        sys.exit(1)
    except Exception as e:
        print(f"Error loading file: {e}")
        sys.exit(1)

def plot_ekf_debug(data):
    """Create comprehensive plots of EKF debugging data."""
    
    # Extract columns
    timestamp = data[:, 0]
    dt = data[:, 1]
    commanded_velocity = data[:, 2]
    steering_angle = data[:, 3]
    rpm = data[:, 4]
    tachometer = data[:, 5]
    delta_tach = data[:, 6]
    tach_to_meters = data[:, 7]
    imu_angular_velocity_raw = data[:, 8]
    imu_angular_velocity_transformed = data[:, 9]
    ekf_x = data[:, 10]
    ekf_y = data[:, 11]
    ekf_theta = data[:, 12]
    ekf_v = data[:, 13]
    ekf_omega = data[:, 14]
    odom_x = data[:, 15]
    odom_y = data[:, 16]
    odom_theta = data[:, 17]
    odom_v = data[:, 18]
    odom_omega = data[:, 19]
    
    # Convert timestamp to relative time
    time = timestamp - timestamp[0]
    
    # Calculate wheel odometry velocity from tachometer
    wheel_velocity = delta_tach * tach_to_meters[0] / dt
    
    # Create figure with subplots
    fig = plt.figure(figsize=(16, 12))
    gs = GridSpec(4, 3, figure=fig, hspace=0.3, wspace=0.3)
    
    # Plot 1: Trajectory (X-Y plot)
    ax1 = fig.add_subplot(gs[0:2, 0])
    ax1.plot(odom_x, odom_y, 'b-', linewidth=2, label='Odometry Path')
    ax1.scatter(odom_x[0], odom_y[0], c='g', s=100, marker='o', label='Start', zorder=5)
    ax1.scatter(odom_x[-1], odom_y[-1], c='r', s=100, marker='x', label='End', zorder=5)
    ax1.set_xlabel('X Position (m)')
    ax1.set_ylabel('Y Position (m)')
    ax1.set_title('Odometry Trajectory')
    ax1.legend()
    ax1.grid(True)
    ax1.axis('equal')
    
    # Plot 2: Position over time
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.plot(time, ekf_x, 'b-', label='X')
    ax2.plot(time, ekf_y, 'r-', label='Y')
    ax2.set_xlabel('Time (s)')
    ax2.set_ylabel('Position (m)')
    ax2.set_title('Position Over Time')
    ax2.legend()
    ax2.grid(True)
    
    # Plot 3: Orientation
    ax3 = fig.add_subplot(gs[0, 2])
    ax3.plot(time, np.rad2deg(ekf_theta), 'g-', linewidth=2)
    ax3.set_xlabel('Time (s)')
    ax3.set_ylabel('Orientation (deg)')
    ax3.set_title('Heading Angle')
    ax3.grid(True)
    
    # Plot 4: Commanded vs Estimated Velocity
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.plot(time, commanded_velocity, 'r-', linewidth=3, label='Commanded (smoothed)', alpha=1.0, zorder=3)
    ax4.plot(time, ekf_v, 'b-', linewidth=2, label='EKF Estimate', alpha=0.8, zorder=2)
    ax4.plot(time, wheel_velocity, 'g:', linewidth=2, label='Wheel Odometry', alpha=0.6, zorder=1)
    ax4.axhline(y=0, color='k', linestyle='--', alpha=0.3, linewidth=0.5)
    ax4.set_xlabel('Time (s)')
    ax4.set_ylabel('Linear Velocity (m/s)')
    ax4.set_title('Velocity Comparison (Commanded=Red, EKF=Blue, Wheel=Green)')
    ax4.legend(loc='best')
    ax4.grid(True, alpha=0.3)
    # Add text showing commanded velocity range
    cmd_min, cmd_max = np.min(commanded_velocity), np.max(commanded_velocity)
    ax4.text(0.02, 0.98, f'Cmd range: [{cmd_min:.3f}, {cmd_max:.3f}] m/s', 
             transform=ax4.transAxes, fontsize=8, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    # Plot 5: Angular Velocity Comparison
    ax5 = fig.add_subplot(gs[1, 2])
    ax5.plot(time, np.rad2deg(ekf_omega), 'b-', linewidth=2, label='EKF Omega')
    ax5.plot(time, imu_angular_velocity_transformed, 'r-', linewidth=1, label='IMU (transformed)', alpha=0.7)
    ax5.set_xlabel('Time (s)')
    ax5.set_ylabel('Angular Velocity (deg/s)')
    ax5.set_title('Angular Velocity Comparison')
    ax5.legend()
    ax5.grid(True)
    
    # Plot 6: Tachometer
    ax6 = fig.add_subplot(gs[2, 0])
    ax6.plot(time, tachometer, 'b-', linewidth=1)
    ax6.set_xlabel('Time (s)')
    ax6.set_ylabel('Tachometer (ticks)')
    ax6.set_title('Raw Tachometer Reading')
    ax6.grid(True)
    
    # Plot 7: Tachometer Delta
    ax7 = fig.add_subplot(gs[2, 1])
    ax7.plot(time, delta_tach, 'g-', linewidth=1)
    ax7.axhline(y=0, color='r', linestyle='--', alpha=0.5)
    ax7.set_xlabel('Time (s)')
    ax7.set_ylabel('Delta Tachometer (ticks)')
    ax7.set_title('Tachometer Change (Wheel Motion)')
    ax7.grid(True)
    
    # Plot 8: RPM
    ax8 = fig.add_subplot(gs[2, 2])
    ax8.plot(time, rpm, 'purple', linewidth=1)
    ax8.axhline(y=0, color='r', linestyle='--', alpha=0.5)
    ax8.set_xlabel('Time (s)')
    ax8.set_ylabel('RPM')
    ax8.set_title('Motor RPM')
    ax8.grid(True)
    
    # Plot 9: Steering Angle
    ax9 = fig.add_subplot(gs[3, 0])
    ax9.plot(time, np.rad2deg(steering_angle), 'orange', linewidth=2)
    ax9.axhline(y=0, color='k', linestyle='--', alpha=0.3)
    ax9.set_xlabel('Time (s)')
    ax9.set_ylabel('Steering Angle (deg)')
    ax9.set_title('Steering Commands')
    ax9.grid(True)
    
    # Plot 10: Time Delta
    ax10 = fig.add_subplot(gs[3, 1])
    ax10.plot(time, dt * 1000, 'cyan', linewidth=1)
    ax10.set_xlabel('Time (s)')
    ax10.set_ylabel('dt (ms)')
    ax10.set_title('Update Time Delta')
    ax10.grid(True)
    
    # Plot 11: IMU Raw vs Transformed
    ax11 = fig.add_subplot(gs[3, 2])
    ax11.plot(time, imu_angular_velocity_raw, 'r-', linewidth=1, label='Raw Z-axis', alpha=0.7)
    ax11.plot(time, imu_angular_velocity_transformed, 'b-', linewidth=1, label='Transformed')
    ax11.axhline(y=0, color='k', linestyle='--', alpha=0.3)
    ax11.set_xlabel('Time (s)')
    ax11.set_ylabel('Angular Velocity (deg/s)')
    ax11.set_title('IMU Frame Transformation')
    ax11.legend()
    ax11.grid(True)
    
    plt.suptitle('EKF Odometry Debug Analysis', fontsize=16, fontweight='bold')
    
    # Print statistics
    print("\n=== EKF Debug Statistics ===")
    print(f"Duration: {time[-1]:.2f} seconds")
    print(f"Samples: {len(time)}")
    print(f"Average dt: {np.mean(dt)*1000:.2f} ms")
    print(f"\nPosition drift:")
    print(f"  Final X: {ekf_x[-1]:.3f} m")
    print(f"  Final Y: {ekf_y[-1]:.3f} m")
    print(f"  Final distance from start: {np.sqrt(ekf_x[-1]**2 + ekf_y[-1]**2):.3f} m")
    print(f"\nCommanded velocity stats:")
    print(f"  Min: {np.min(commanded_velocity):.3f} m/s")
    print(f"  Max: {np.max(commanded_velocity):.3f} m/s")
    print(f"  Mean: {np.mean(np.abs(commanded_velocity)):.3f} m/s")
    print(f"  Std: {np.std(commanded_velocity):.3f} m/s")
    print(f"  Stationary time: {np.sum(np.abs(commanded_velocity) < 0.01) / len(time) * time[-1]:.2f} s")
    print(f"\nEKF velocity stats:")
    print(f"  Mean: {np.mean(np.abs(ekf_v)):.3f} m/s")
    print(f"  Max: {np.max(np.abs(ekf_v)):.3f} m/s")
    print(f"\nWheel velocity stats:")
    print(f"  Mean: {np.mean(np.abs(wheel_velocity)):.3f} m/s")
    print(f"  Max: {np.max(np.abs(wheel_velocity)):.3f} m/s")
    
    # Check for potential issues
    print("\n=== Potential Issues ===")
    issues_found = False
    
    if np.max(np.abs(delta_tach)) == 0:
        print("WARNING: No tachometer movement detected!")
        issues_found = True
    
    if np.max(np.abs(imu_angular_velocity_transformed)) == 0:
        print("WARNING: No IMU angular velocity detected!")
        issues_found = True
    
    if np.max(np.abs(commanded_velocity)) == 0 and np.max(np.abs(wheel_velocity)) > 0.01:
        print("WARNING: Commanded velocity is always zero but wheels are moving!")
        print("  This indicates commanded velocity is not being logged correctly.")
        issues_found = True
    
    if np.mean(np.abs(commanded_velocity)) < 0.01 and np.sqrt(ekf_x[-1]**2 + ekf_y[-1]**2) > 0.1:
        print(f"WARNING: Significant drift ({np.sqrt(ekf_x[-1]**2 + ekf_y[-1]**2):.3f}m) with near-zero commanded velocity!")
        issues_found = True
    
    # Check if commanded velocity matches wheel velocity reasonably
    nonzero_idx = np.abs(wheel_velocity) > 0.01
    if np.sum(nonzero_idx) > 10:
        cmd_vs_wheel_diff = np.mean(np.abs(commanded_velocity[nonzero_idx] - wheel_velocity[nonzero_idx]))
        if cmd_vs_wheel_diff > 0.5:
            print(f"WARNING: Large discrepancy between commanded ({np.mean(np.abs(commanded_velocity[nonzero_idx])):.3f} m/s) " + 
                  f"and wheel velocity ({np.mean(np.abs(wheel_velocity[nonzero_idx])):.3f} m/s)")
            issues_found = True
    
    if not issues_found:
        print("No obvious issues detected.")
    
    return fig

def main():
    """Main function."""
    # Get CSV file path from command line or use default
    default_csv = '/home/orin/roboracer_ws/data/debug/ekf_debug.csv'
    csv_file = sys.argv[1] if len(sys.argv) > 1 else default_csv
    
    print(f"Loading EKF debug data from: {csv_file}")
    data = load_data(csv_file)
    
    print("Generating plots...")
    fig = plot_ekf_debug(data)
    
    # Create output directory if it doesn't exist
    output_dir = '/home/orin/roboracer_ws/data/debug'
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate timestamped output filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = os.path.join(output_dir, f'ekf_debug_plots_{timestamp}.png')
    
    # Save figure
    fig.savefig(output_file, dpi=150, bbox_inches='tight')
    print(f"\nPlots saved to: {output_file}")
    
    # Also create a symlink to latest for convenience
    latest_link = os.path.join(output_dir, 'ekf_debug_plots_latest.png')
    if os.path.exists(latest_link):
        os.remove(latest_link)
    os.symlink(os.path.basename(output_file), latest_link)
    print(f"Latest plots link: {latest_link}")
    
    # Copy CSV with timestamp for archival
    csv_archive = os.path.join(output_dir, f'ekf_debug_{timestamp}.csv')
    import shutil
    if csv_file != csv_archive:
        shutil.copy2(csv_file, csv_archive)
        print(f"CSV archived to: {csv_archive}")
    
    # Close figure to free memory (don't show - no display required)
    plt.close(fig)
    print("\nAnalysis complete! View plots at:")
    print(f"  {latest_link}")

if __name__ == '__main__':
    main()

