name: Build-Test
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    container:
      image: natester/roboracer_sim:latest
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Get amrl_msgs
        run: |
          cd $HOME/roboracer_ros_ws/src
          git clone -b ros2 https://github.com/ut-amrl/amrl_msgs.git
          cd amrl_msgs
          make
      - name: Get amrl_maps
        run: |
          cd $HOME/roboracer_ros_ws/src
          git clone -b master https://github.com/ut-amrl/amrl_maps.git
      - name: Run build
        run: |
          cd $HOME/roboracer_ros_ws
          olcon build --cmake-args -DCMAKE_BUILD_MODE="Software"
