name: Build-Test
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    container:
      image: natester/roboracer_sim:latest
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
      - name: Get amrl_msgs
        run: |
          mkdir -p $HOME/roboracer_sim_ws/src
          cd $HOME/roboracer_sim_ws/src
          git clone -b master https://github.com/ut-amrl/amrl_msgs.git
      - name: Get amrl_maps
        run: |
          mkdir -p $HOME/roboracer_sim_ws/src
          cd $HOME/roboracer_sim_ws/src
          git clone -b ros2 https://github.com/ut-amrl/amrl_maps.git
      - name: Run build
        run: |
          cd $HOME/roboracer_sim_ws
          source /opt/ros/humble/setup.bash
          colcon build --cmake-args -DCMAKE_BUILD_MODE="Software"
