name: Build-Test
on: push

jobs:
  build-test:
    name: Build test
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy-ros-base

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git python3-colcon-common-extensions \
            libgflags-dev libgoogle-glog-dev liblua5.1-0-dev \
            libboost-all-dev libqt5websockets5-dev libqt5opengl5-dev qtbase5-dev \
            ros-jazzy-ament-index-cpp ros-jazzy-tf2-ros \
            ros-jazzy-tf2-geometry-msgs ros-jazzy-urg-node ros-jazzy-joy

      - name: Create workspace
        run: |
          mkdir -p "$GITHUB_WORKSPACE/../deps_ws/src"
          ln -s "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/../deps_ws/src/ut_automata"
          git clone https://github.com/ut-amrl/amrl_msgs.git "$GITHUB_WORKSPACE/../deps_ws/src/amrl_msgs"
          git clone https://github.com/ut-amrl/amrl_maps.git "$GITHUB_WORKSPACE/../deps_ws/src/amrl_maps"

      - name: Run build
        working-directory: ${{ github.workspace }}/../deps_ws
        run: |
          . /opt/ros/jazzy/setup.sh
          colcon build --packages-up-to ut_automata --cmake-args -DCMAKE_BUILD_TYPE=Release
